export { default as api } from "./api"
export * from "./authService"
export { fetchCart, putCartItems } from "./cartService"
export { fetchComments, postComment } from "./commentService"
export { fetchOrders, postOrder } from "./orderService"
export { fetchShippingAddress } from "./paymentService"
export { fetchCategories, fetchProducts } from "./productService"
export { fetchCommunes, fetchProvinces } from "./provinceService"
export { postGetImageSignature, postUploadImage } from "./uploadService"
export { postUpdateUserInfo } from "./userService"
